src/lib/types/IChannel.ts, src/lib/wsHandler/INIT.ws.ts, src/routes/channel/+page.svelte
チャンネルのアーカイブトグルをできるようにした
チャンネルブラウザではリアルタイムで受け取った情報を表示に適用するように
=> Archive channel

src/lib/components/unique/toast.svelte, src/lib/repositories/serverRepository.ts, src/lib/types/IServer.ts, src/lib/wsHandler/channel/sendMessage.ts, src/routes/setting/+page.svelte, src/routes/setting/server-manage/+page.svelte
=> Server manage

src/lib/wsHandler/INIT.ws.ts
=> Fix ws not reconnecting

src/routes/setting/profile-setting/+page.svelte
=> fix:ProfileSettingレイアウト調整

src/lib/components/role-setting/CreateRole.svelte, src/lib/components/role-setting/DeleteRole.svelte, src/lib/repositories/RepositoryFactory.ts, src/lib/repositories/roleRepository.ts, src/lib/repositories/serverRepository.ts, src/lib/types/IRole.ts, src/routes/setting/role-setting/+page.svelte
ロールの管理ページ。
ロールの権限変更、情報変更、作成、削除。
レスポンシブにも対応されたつもり
=> 15 manage role

src/lib/repositories/userRepository.ts, src/routes/setting/profile-setting/+page.svelte
=> feat:パスワード変更の追加(#14)

src/lib/components/Drawer/Drawer.svelte, src/lib/middleware.ts, src/lib/repositories/messageRepository.ts, src/lib/store/messageReadTime.ts, src/lib/types/IMessage.ts, src/lib/utils/updateReadTime.ts, src/lib/wsHandler/INIT.ws.ts, src/lib/wsHandler/channel/sendMessage.ts, src/lib/wsHandler/message/ReadTimeUpdated.ts, src/routes/channel/[id]/+page.svelte, src/routes/channel/[id]/channelMessage.ts
=> Craete read time

src/lib/components/Drawer/Drawer.svelte
=> fix:チャンネル一覧のはみ出し修正

src/routes/channel/[id]/channelMessage.ts
チャンネルメッセージに同じメッセージが入ってくるバグの根本修正
=> fix: 重複メッセージを除外するための修正

src/routes/channel/[id]/+page.svelte, src/routes/channel/[id]/hoverMenu.svelte
とりあえずメッセージにホバーしたら三点リーダーが出てきて
押したらDropDown開くとこまでやった
DropDown内のボタンは#18 とかで適宜対応
=> add:ホバーメニュー追加(#33)

src/lib/components/channel/Messageinput/FileChip.svelte, src/lib/repositories/messageRepository.ts, src/lib/types/IMessage.ts, src/lib/utils/DisplaySizeForHuman.ts, src/routes/channel/[id]/+page.svelte, src/routes/channel/[id]/FilePreview.svelte, src/routes/channel/[id]/MessageInput.svelte, src/routes/channel/[id]/channelMessage.ts
ファイルのアップロード
バックエンドのブランチ( https://github.com/giracle-dev/giracle-backend/pull/49 )は`FileUploads`
=> File upload

src/lib/components/Drawer/Drawer.svelte, src/lib/repositories/messageRepository.ts, src/lib/types/IMessage.ts, src/routes/+layout.svelte, src/routes/channel/[id]/FilePreview.svelte, src/routes/search/+page.svelte
メッセージの条件付き検索
ユーザーIdとチャンネルIdの絞り込みもあるけど一旦URLプレビューとファイル添付の条件指定のみ対応
=> Search message

src/lib/repositories/messageRepository.ts, src/lib/utils/updateReadTime.ts, src/lib/wsHandler/channel/sendMessage.ts, src/routes/channel/[id]/+page.svelte, src/routes/channel/[id]/channelMessage.ts
=> Fix history fetching

src/lib/components/unique/ChannelSearchBar.svelte, src/lib/components/unique/SearchChannelAndSelect.svelte, src/lib/repositories/channelRepository.ts, src/lib/repositories/serverRepository.ts, src/lib/store/serverInfo.ts, src/lib/types/IChannel.ts, src/lib/types/IServer.ts, src/routes/setting/server-manage/+page.svelte
アカウント登録時に参加するチャンネルを設定できるようにした
バックエンドのブランチ : `DefaultJoinChannel` https://github.com/giracle-dev/giracle-backend/pull/58
=> Default channel join

src/routes/channel/[id]/+page.svelte
=> Same users messages display

src/routes/channel/[id]/hoverMenu.svelte
=> Fix hover gatagata

src/lib/wsHandler/INIT.ws.ts, src/routes/+layout.svelte, src/routes/channel/[id]/+page.svelte
WebSocket接続が切れたときにアラート表示をするように
=> Ws status display

src/lib/store/messageReadTime.ts, src/routes/+layout.svelte
=> Display new on tab

src/routes/channel/[id]/MessageInput.svelte
メンションするときのユーザー選択画面で一番最初のユーザーが選択されるように、あと選択時のユーザー名文字色を調整しただけ
=> Better select mention

src/lib/wsHandler/INIT.ws.ts
=> Fix sync online user

src/lib/wsHandler/INIT.ws.ts, src/lib/wsHandler/channel/sendMessage.ts, src/routes/+layout.svelte
=> Notification

src/lib/components/Drawer/Drawer.svelte
=> Format drawer button design

src/lib/middleware.ts, src/lib/store/myRolePower.ts, src/lib/store/role.ts, src/routes/channel/[id]/+page.svelte, src/routes/channel/[id]/ChannelInfoSidebar.svelte, src/routes/setting/+page.svelte
=> Control display UI with role

src/lib/store/myRolePower.ts, src/lib/wsHandler/INIT.ws.ts, src/lib/wsHandler/role/roleCreated.ts, src/lib/wsHandler/role/roleDeleted.ts, src/lib/wsHandler/role/roleLinked.ts, src/lib/wsHandler/role/roleUnlinked.ts, src/lib/wsHandler/role/roleUpdated.ts
=> Ws role handler

src/routes/channel/[id]/+page.svelte, src/routes/channel/[id]/channelMessage.ts
チャンネルアクセス時にちょっとだけ上にスクロールされてしまうせいでその後にくるメッセージへスクロールされなかったりする。
=> Fix eerie scroll

src/lib/repositories/serverRepository.ts, src/lib/types/IServer.ts, src/routes/channel/[id]/+page.svelte, src/routes/channel/[id]/SystemMessage.svelte, src/routes/setting/server-manage/+page.svelte
=> System message

package.json, src/routes/channel/[id]/+page.svelte
URLプレビューの画像見切れてた、あとfavicon表示されない問題を修正
=> Fix url preview image
